### ISSUE TITLE
Fills up all of system memory and then freezes calculator.

### ISSUE THREAD

**Issue by aquamarine-axo** [Techcrafter/PROTOX#1]
First of all, I understand that this software is licensed under the GPL, which means the program has no warrenty. However, I would still like to report that upon launching the application on my calculator, it immediately filled up the rest of my memory (I had 130k free), kept throwing errors, and now the calculator will not turn on. After trying to re-send the 5.8.0 OS bundle, the calculator is not recognized by TI Connect CE. The calculator will also not turn on the display anymore.

Calculator information: OS 5.8.0
Shell: CEsium
Please ask me if you need more information.

**Comment by Techcrafter** [comment]
Are you talking about RAM or Archive memory? PROTOX does need a lot of RAM to run because of its many graphics, although even if it does run out of memory, you should be able to fix this by simply pushing the reset button to clear your RAM. Also, OS version 5.8.0 doesn't support running ASM programs normally as far as I know, so your issue might be caused by whatever "exploit" you used to run the program. Have you tried to simply take out the battery for a few minutes and put it back in?
I hope I was able to help!
